<?php

return [
    'sponsors' => [
        1 => [
            'name'          => 'Tech Corp',
            'name_en'       => 'Tech Corp',
            'name_ar'       => 'تيك كورب',
            'tier'          => 'main',
            'description_en'=> 'Driving the strategic vision for global ecommerce innovation.',
            'description_ar'=> 'تقود الرؤية الاستراتيجية للابتكار في مجال التجارة الإلكترونية العالمية.',
            'url'           => 'https://example.com',
            'logo_path'     => null,
            'display_order' => 1,
            'is_active'     => true,
        ],
        2 => [
            'name'          => 'Innovation Labs',
            'name_en'       => 'Innovation Labs',
            'name_ar'       => 'مختبرات الابتكار',
            'tier'          => 'main',
            'description_en'=> 'Building immersive expo experiences with future-ready technologies.',
            'description_ar'=> 'تبني تجارب معارض غامرة باستخدام تقنيات جاهزة للمستقبل.',
            'url'           => 'https://example.com/innovation',
            'logo_path'     => null,
            'display_order' => 2,
            'is_active'     => true,
        ],
        3 => [
            'name'          => 'Global Finance',
            'name_en'       => 'Global Finance',
            'name_ar'       => 'جلوبال فاينانس',
            'tier'          => 'gold',
            'description_en'=> 'Financial partner empowering exhibitors with tailored growth programs.',
            'description_ar'=> 'شريك مالي يمكّن العارضين من خلال برامج نمو مخصصة.',
            'url'           => 'https://example.com/global',
            'logo_path'     => null,
            'display_order' => 3,
            'is_active'     => true,
        ],
        4 => [
            'name'          => 'Cloud Systems',
            'name_en'       => 'Cloud Systems',
            'name_ar'       => 'كلود سيستمز',
            'tier'          => 'gold',
            'description_en'=> 'Cloud-native infrastructure powering reliable commerce operations.',
            'description_ar'=> 'بنية سحابية أصلية تدعم عمليات التجارة الموثوقة.',
            'url'           => 'https://example.com/cloud',
            'logo_path'     => null,
            'display_order' => 4,
            'is_active'     => true,
        ],
        5 => [
            'name'          => 'Data Dynamics',
            'name_en'       => 'Data Dynamics',
            'name_ar'       => 'داتا دايناميكس',
            'tier'          => 'gold',
            'description_en'=> 'Analytics leader delivering insight-driven marketing decisions.',
            'description_ar'=> 'رائدة في التحليلات تقدم قرارات تسويقية مدفوعة بالبيانات.',
            'url'           => 'https://example.com/data',
            'logo_path'     => null,
            'display_order' => 5,
            'is_active'     => true,
        ],
        6 => [
            'name'          => 'Green Energy',
            'name_en'       => 'Green Energy',
            'name_ar'       => 'جرين إنيرجي',
            'tier'          => 'silver',
            'description_en'=> 'Sustainable energy partner keeping the expo efficient and clean.',
            'description_ar'=> 'شريك طاقة مستدامة يحافظ على كفاءة المعرض ونظافته.',
            'url'           => 'https://example.com/green',
            'logo_path'     => null,
            'display_order' => 6,
            'is_active'     => true,
        ],
        7 => [
            'name'          => 'Smart Solutions',
            'name_en'       => 'Smart Solutions',
            'name_ar'       => 'سمارت سلوشنز',
            'tier'          => 'silver',
            'description_en'=> 'Automation experts connecting attendees with seamless journeys.',
            'description_ar'=> 'خبراء الأتمتة الذين يربطون الزوار بتجارب سلسة.',
            'url'           => 'https://example.com/smart',
            'logo_path'     => null,
            'display_order' => 7,
            'is_active'     => true,
        ],
        8 => [
            'name'          => 'Future Tech',
            'name_en'       => 'Future Tech',
            'name_ar'       => 'فيوتشر تك',
            'tier'          => 'silver',
            'description_en'=> 'Emerging tech studio showcasing bold prototypes and pilots.',
            'description_ar'=> 'استوديو تقني ناشئ يعرض نماذج أولية جريئة ومشروعات تجريبية.',
            'url'           => 'https://example.com/future',
            'logo_path'     => null,
            'display_order' => 8,
            'is_active'     => true,
        ],
    ],
    'organizers' => [
        1 => [
            'name'           => 'Umbrella Events',
            'name_ar'        => 'أمبريلا إيفنتس',
            'description_en' => 'Lead organizer overseeing the full conference experience.',
            'description_ar' => 'المنظم الرئيسي الذي يشرف على تجربة المؤتمر الكاملة.',
            'url'            => 'https://example.com/umbrella',
            'logo_path'      => null,
            'display_order'  => 1,
            'is_active'      => true,
        ],
        2 => [
            'name'           => 'Riyadh Expo Authority',
            'name_ar'        => 'هيئة معارض الرياض',
            'description_en' => 'Venue partner ensuring seamless operations.',
            'description_ar' => 'شريك الموقع الذي يضمن سير العمليات بسلاسة.',
            'url'            => 'https://example.com/riyadh-expo',
            'logo_path'      => null,
            'display_order'  => 2,
            'is_active'      => true,
        ],
        3 => [
            'name'           => 'Visionary Media',
            'name_ar'        => 'رؤية ميديا',
            'description_en' => 'Media partner amplifying event coverage.',
            'description_ar' => 'شريك إعلامي يعزز تغطية الحدث.',
            'url'            => 'https://example.com/visionary',
            'logo_path'      => null,
            'display_order'  => 3,
            'is_active'      => true,
        ],
    ],
    'participants' => [
        1 => [
            'name'           => 'Saudi Aramco',
            'name_ar'        => 'أرامكو السعودية',
            'description_en' => 'Global leader in energy solutions.',
            'description_ar' => 'رائد عالمي في حلول الطاقة.',
            'url'            => 'https://www.aramco.com',
            'logo_path'      => null,
            'display_order'  => 1,
            'is_active'      => true,
        ],
        2 => [
            'name'           => 'SABIC',
            'name_ar'        => 'سابك',
            'description_en' => 'Petrochemicals and manufacturing excellence.',
            'description_ar' => 'تميز في البتروكيماويات والتصنيع.',
            'url'            => 'https://www.sabic.com',
            'logo_path'      => null,
            'display_order'  => 2,
            'is_active'      => true,
        ],
        3 => [
            'name'           => 'STC',
            'name_ar'        => 'اس تي سي',
            'description_en' => 'Leading telecommunications provider.',
            'description_ar' => 'مزود اتصالات رائد.',
            'url'            => 'https://www.stc.com.sa',
            'logo_path'      => null,
            'display_order'  => 3,
            'is_active'      => true,
        ],
        4 => [
            'name'           => 'Al Rajhi Bank',
            'name_ar'        => 'مصرف الراجحي',
            'description_en' => 'Islamic banking pioneer.',
            'description_ar' => 'رائد في الخدمات المصرفية الإسلامية.',
            'url'            => 'https://www.alrajhibank.com.sa',
            'logo_path'      => null,
            'display_order'  => 4,
            'is_active'      => true,
        ],
        5 => [
            'name'           => 'NEOM',
            'name_ar'        => 'نيوم',
            'description_en' => 'Building the future of living.',
            'description_ar' => 'بناء مستقبل الحياة.',
            'url'            => 'https://www.neom.com',
            'logo_path'      => null,
            'display_order'  => 5,
            'is_active'      => true,
        ],
        6 => [
            'name'           => 'Red Sea Global',
            'name_ar'        => 'البحر الأحمر للتطوير',
            'description_en' => 'Sustainable tourism development.',
            'description_ar' => 'تطوير السياحة المستدامة.',
            'url'            => 'https://www.redseaglobal.com',
            'logo_path'      => null,
            'display_order'  => 6,
            'is_active'      => true,
        ],
    ],
];
