<?php

return [
    'sponsors' => [
        1 => [
            'name'          => 'Tech Corp',
            'name_en'       => 'Tech Corp',
            'name_ar'       => 'تيك كورب',
            'tier'          => 'main',
            'logo_path'     => null,
            'display_order' => 1,
            'is_active'     => true,
        ],
        2 => [
            'name'          => 'Innovation Labs',
            'name_en'       => 'Innovation Labs',
            'name_ar'       => 'مختبرات الابتكار',
            'tier'          => 'main',
            'logo_path'     => null,
            'display_order' => 2,
            'is_active'     => true,
        ],
        3 => [
            'name'          => 'Global Finance',
            'name_en'       => 'Global Finance',
            'name_ar'       => 'جلوبال فاينانس',
            'tier'          => 'gold',
            'logo_path'     => null,
            'display_order' => 3,
            'is_active'     => true,
        ],
        4 => [
            'name'          => 'Cloud Systems',
            'name_en'       => 'Cloud Systems',
            'name_ar'       => 'كلود سيستمز',
            'tier'          => 'gold',
            'logo_path'     => null,
            'display_order' => 4,
            'is_active'     => true,
        ],
        5 => [
            'name'          => 'Data Dynamics',
            'name_en'       => 'Data Dynamics',
            'name_ar'       => 'داتا دايناميكس',
            'tier'          => 'gold',
            'logo_path'     => null,
            'display_order' => 5,
            'is_active'     => true,
        ],
        6 => [
            'name'          => 'Green Energy',
            'name_en'       => 'Green Energy',
            'name_ar'       => 'جرين إنيرجي',
            'tier'          => 'silver',
            'logo_path'     => null,
            'display_order' => 6,
            'is_active'     => true,
        ],
        7 => [
            'name'          => 'Smart Solutions',
            'name_en'       => 'Smart Solutions',
            'name_ar'       => 'سمارت سلوشنز',
            'tier'          => 'silver',
            'logo_path'     => null,
            'display_order' => 7,
            'is_active'     => true,
        ],
        8 => [
            'name'          => 'Future Tech',
            'name_en'       => 'Future Tech',
            'name_ar'       => 'فيوتشر تك',
            'tier'          => 'silver',
            'logo_path'     => null,
            'display_order' => 8,
            'is_active'     => true,
        ],
    ],
    'organizers' => [
        1 => [
            'name'           => 'Umbrella Events',
            'name_ar'        => 'أمبريلا إيفنتس',
            'description_en' => 'Lead organizer overseeing the full conference experience.',
            'description_ar' => 'المنظم الرئيسي الذي يشرف على تجربة المؤتمر الكاملة.',
            'url'            => 'https://example.com/umbrella',
            'logo_path'      => null,
            'display_order'  => 1,
            'is_active'      => true,
        ],
        2 => [
            'name'           => 'Riyadh Expo Authority',
            'name_ar'        => 'هيئة معارض الرياض',
            'description_en' => 'Venue partner ensuring seamless operations.',
            'description_ar' => 'شريك الموقع الذي يضمن سير العمليات بسلاسة.',
            'url'            => 'https://example.com/riyadh-expo',
            'logo_path'      => null,
            'display_order'  => 2,
            'is_active'      => true,
        ],
        3 => [
            'name'           => 'Visionary Media',
            'name_ar'        => 'رؤية ميديا',
            'description_en' => 'Media partner amplifying event coverage.',
            'description_ar' => 'شريك إعلامي يعزز تغطية الحدث.',
            'url'            => 'https://example.com/visionary',
            'logo_path'      => null,
            'display_order'  => 3,
            'is_active'      => true,
        ],
    ],
    'participants' => [
        1 => [
            'name'           => 'Saudi Aramco',
            'name_ar'        => 'أرامكو السعودية',
            'url'            => 'https://www.aramco.com',
            'logo_path'      => null,
            'display_order'  => 1,
            'is_active'      => true,
        ],
        2 => [
            'name'           => 'SABIC',
            'name_ar'        => 'سابك',
            'url'            => 'https://www.sabic.com',
            'logo_path'      => null,
            'display_order'  => 2,
            'is_active'      => true,
        ],
        3 => [
            'name'           => 'STC',
            'name_ar'        => 'اس تي سي',
            'url'            => 'https://www.stc.com.sa',
            'logo_path'      => null,
            'display_order'  => 3,
            'is_active'      => true,
        ],
        4 => [
            'name'           => 'Al Rajhi Bank',
            'name_ar'        => 'مصرف الراجحي',
            'url'            => 'https://www.alrajhibank.com.sa',
            'logo_path'      => null,
            'display_order'  => 4,
            'is_active'      => true,
        ],
        5 => [
            'name'           => 'NEOM',
            'name_ar'        => 'نيوم',
            'url'            => 'https://www.neom.com',
            'logo_path'      => null,
            'display_order'  => 5,
            'is_active'      => true,
        ],
        6 => [
            'name'           => 'Red Sea Global',
            'name_ar'        => 'البحر الأحمر للتطوير',
            'url'            => 'https://www.redseaglobal.com',
            'logo_path'      => null,
            'display_order'  => 6,
            'is_active'      => true,
        ],
    ],
];
