<?php

return [
    'sponsors' => [
        1 => [
            'name'          => 'Tech Corp',
            'tier'          => 'main',
            'url'           => 'https://example.com',
            'logo_path'     => null,
            'display_order' => 1,
            'is_active'     => true,
        ],
        2 => [
            'name'          => 'Innovation Labs',
            'tier'          => 'main',
            'url'           => 'https://example.com/innovation',
            'logo_path'     => null,
            'display_order' => 2,
            'is_active'     => true,
        ],
        3 => [
            'name'          => 'Global Finance',
            'tier'          => 'gold',
            'url'           => 'https://example.com/global',
            'logo_path'     => null,
            'display_order' => 3,
            'is_active'     => true,
        ],
        4 => [
            'name'          => 'Cloud Systems',
            'tier'          => 'gold',
            'url'           => 'https://example.com/cloud',
            'logo_path'     => null,
            'display_order' => 4,
            'is_active'     => true,
        ],
        5 => [
            'name'          => 'Data Dynamics',
            'tier'          => 'gold',
            'url'           => 'https://example.com/data',
            'logo_path'     => null,
            'display_order' => 5,
            'is_active'     => true,
        ],
        6 => [
            'name'          => 'Green Energy',
            'tier'          => 'silver',
            'url'           => 'https://example.com/green',
            'logo_path'     => null,
            'display_order' => 6,
            'is_active'     => true,
        ],
        7 => [
            'name'          => 'Smart Solutions',
            'tier'          => 'silver',
            'url'           => 'https://example.com/smart',
            'logo_path'     => null,
            'display_order' => 7,
            'is_active'     => true,
        ],
        8 => [
            'name'          => 'Future Tech',
            'tier'          => 'silver',
            'url'           => 'https://example.com/future',
            'logo_path'     => null,
            'display_order' => 8,
            'is_active'     => true,
        ],
    ],
    'participants' => [
        1 => [
            'name'           => 'Saudi Aramco',
            'description_en' => 'Global leader in energy solutions.',
            'description_ar' => 'رائد عالمي في حلول الطاقة.',
            'url'            => 'https://www.aramco.com',
            'logo_path'      => null,
            'display_order'  => 1,
            'is_active'      => true,
        ],
        2 => [
            'name'           => 'SABIC',
            'description_en' => 'Petrochemicals and manufacturing excellence.',
            'description_ar' => 'تميز في البتروكيماويات والتصنيع.',
            'url'            => 'https://www.sabic.com',
            'logo_path'      => null,
            'display_order'  => 2,
            'is_active'      => true,
        ],
        3 => [
            'name'           => 'STC',
            'description_en' => 'Leading telecommunications provider.',
            'description_ar' => 'مزود اتصالات رائد.',
            'url'            => 'https://www.stc.com.sa',
            'logo_path'      => null,
            'display_order'  => 3,
            'is_active'      => true,
        ],
        4 => [
            'name'           => 'Al Rajhi Bank',
            'description_en' => 'Islamic banking pioneer.',
            'description_ar' => 'رائد في الخدمات المصرفية الإسلامية.',
            'url'            => 'https://www.alrajhibank.com.sa',
            'logo_path'      => null,
            'display_order'  => 4,
            'is_active'      => true,
        ],
        5 => [
            'name'           => 'NEOM',
            'description_en' => 'Building the future of living.',
            'description_ar' => 'بناء مستقبل الحياة.',
            'url'            => 'https://www.neom.com',
            'logo_path'      => null,
            'display_order'  => 5,
            'is_active'      => true,
        ],
        6 => [
            'name'           => 'Red Sea Global',
            'description_en' => 'Sustainable tourism development.',
            'description_ar' => 'تطوير السياحة المستدامة.',
            'url'            => 'https://www.redseaglobal.com',
            'logo_path'      => null,
            'display_order'  => 6,
            'is_active'      => true,
        ],
    ],
];
